/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexión.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase que da de baja a un propietario
 *
 * @author Sergio Marco
 * @version 23/05/2017
 */
public class VentanaBajaPropietario extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Conexion conn;

    /**
     * Creates new form VentanaBajaPropietario
     *
     * @param conn parámetro que pasa la conexión
     */
    public VentanaBajaPropietario(Conexion conn) {
        this.conn = conn;
        initComponents();
        //Por defecto los botones estarán desactivados
        tNombre.setEnabled(false);
        tApellido.setEnabled(false);
        tLefono.setEnabled(false);
        tProvincia.setEnabled(false);
        //Cojo el modelo de la tabla
        modelo = (DefaultTableModel) tabla.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tApellido = new javax.swing.JTextField();
        tLefono = new javax.swing.JTextField();
        tProvincia = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        bVehiculo = new javax.swing.JButton();
        bProp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDniActionPerformed(evt);
            }
        });

        jLabel1.setText("DNI:");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("APELLIDO:");

        jLabel4.setText("PROVINCIA:");

        jLabel5.setText("TELEFONO:");

        bCancelar.setText("CANCELAR");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bVehiculo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bVehiculo.setText("ELIMINAR VEHICULOS");
        bVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVehiculoActionPerformed(evt);
            }
        });

        bProp.setText("ELIMINAR PROPIETARIO");
        bProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPropActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Modelo", "Año", "Propietario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(274, 274, 274)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(tDni)
                    .addComponent(tLefono)
                    .addComponent(tApellido)
                    .addComponent(tProvincia)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tApellido)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLefono, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tProvincia)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProp))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Comprueba que el dni sea correcto y no uno inventado
     *
     * @param dni parámetro que le pasa el dni introducido para validar.
     * @return
     */
    private boolean compruebaDNI(String dni) {
        String letras = "TRWAGMYFPDXBNJZSQVHLCKE";
        String numeros = "0123456789";
        String NIE = "XYZ";
        int pos;
        //Si no tiene longitud 9 ya ni sigo
        if (dni.length() == 9) {
            String primera = dni.substring(0, 1);
            //Si la primera letra es de dni extranjero
            if (primera.toUpperCase().indexOf(NIE) != -1) {
                //Si los caracteres del 1 al 7 son numéricos sigo con la comprobación
                //si hay alguno que no lo es, el DNI ya es incorrecto
                for (int i = 1; i < dni.length() - 1; i++) {
                    if (numeros.indexOf(dni.substring(i, i + 1)) == -1) {
                        return false;
                    }
                }

                //Sustituyo la primera letra del NIE por el número al que se corresponde para
                //calcular el dígito de control.
                String num;
                if (primera.toUpperCase().equals("X")) {
                    num = "0";
                } else if (primera.toUpperCase().equals("Y")) {
                    num = "1";
                } else {
                    num = "2";
                }
                //Calculo y compruebo el dígito de control
                //Si está mal ya devuelvo false
                int numDni = Integer.parseInt("0" + dni.substring(1, 7));
                pos = numDni % 23;
                if (!dni.substring(7, 8).equalsIgnoreCase(letras.substring(pos, pos + 1))) {
                    return false;
                }
                //Si no es un DNI extranjero, sino que es de un español
            } else {
                //Compruebo que todos los caracteres menos el último son
                //dígitos, si no devuelvo false
                for (int i = 0; i < dni.length() - 1; i++) {
                    if (numeros.indexOf(dni.substring(i, i + 1)) == -1) {
                        return false;
                    }
                }
                //Calculo el dígito de control
                int numDni = Integer.parseInt(dni.substring(0, 8));
                pos = numDni % 23;
                if (!dni.substring(8, 9).equalsIgnoreCase(letras.substring(pos, pos + 1))) {
                    return false;
                }
            }
            //Si ha llegado hasta aquí es porque es correcto
            return true;
        }
        return false;
    }

    /**
     * Al introducir el dni correcto, mostrará toda la información del
     * propietario
     *
     * @param evt
     */
    private void tDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDniActionPerformed
        ResultSet rs = null;
        PreparedStatement ps = null;
        try {
            //Si el dni no es correcto mostrará un mensaje de error y deberá introducirlo otra vez
            if (!compruebaDNI(tDni.getText())) {
                JOptionPane.showMessageDialog(this, "!DNI INCORRECTO¡", "DNI incorrecto", JOptionPane.ERROR_MESSAGE);
                tDni.setText("");
            } else {
                //Si es correcto se habilitan los botones
                tNombre.setEnabled(true);
                tApellido.setEnabled(true);
                tLefono.setEnabled(true);
                tProvincia.setEnabled(true);
                //Lanzamos la consulta para mostrar todos los datos
                ps = conn.prepararSentencia("SELECT * FROM PROPIETARIO WHERE DNI LIKE ?;");
                //Le damos valor al comodín de la consulta
                ps.setString(1, tDni.getText());
                //Ejecutamos la consulta
                rs = ps.executeQuery();
                //Si el propietario existe rellenamos los campos con sus datos
                if (rs.next()) {
                    tNombre.setText(rs.getString(2));
                    tApellido.setText(rs.getString(3));
                    tLefono.setText(rs.getString(4));
                    tProvincia.setText(rs.getString(5));
                } else {
                    //Si no existe mostramos mensaje de error
                    JOptionPane.showMessageDialog(this, "Este Propietario no existe en la base de datos", "Usuario inexistente", JOptionPane.ERROR_MESSAGE);

                }
                //Método que rellena la tabla con los vehículos del propietario
                rellenaTabla();
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            // Cerrar statement
            if (ps != null) {
                try {
                    ps.close();
                } catch (SQLException ex) {
                    ex.getMessage();
                }
            }
        }
    }//GEN-LAST:event_tDniActionPerformed
    /**
     * Al pulsar este botón se vaciarán todos los campos
     *
     * @param evt parámetro que llama al evento que vaciará todos los campos
     */
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
       limpiarDatos();
    }//GEN-LAST:event_bCancelarActionPerformed
   /**
    * Método que deja todos los campos y tablas vacíos.
    */
    private void limpiarDatos(){
        tDni.setText("");
        tNombre.setText("");
        tApellido.setText("");
        tLefono.setText("");
        tProvincia.setText("");
        tNombre.setEnabled(false);
        tApellido.setEnabled(false);
        tLefono.setEnabled(false);
        tProvincia.setEnabled(false);
        //Método que borra los datos de la tabla
        LimpiarTabla();
   }
    /**
     * Método que deja la tabla en blanco
     */
    private void LimpiarTabla() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    /**
     * Método que refresca los datos de la tabla
     */
    private void RefrescarTabla() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        rellenaTabla();
    }

    /**
     * Al pulsar este botón se borrarán los vehículos de el propietario
     *
     * @param evt parámetro que llama al evento que borra los vehículos de un
     * propietario
     */
    private void bVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVehiculoActionPerformed
        PreparedStatement ps = null;
        try {
            //Si el dni es incorrecto mostrará el error y deberemos volver a escribirlo
            if (!compruebaDNI(tDni.getText())) {
                JOptionPane.showMessageDialog(this, "!DNI INCORRECTO¡", "DNI incorrecto", JOptionPane.ERROR_MESSAGE);
                tDni.setText("");
            } else {
                //Si es correcto se lanza la consulta
                ps = conn.prepararSentencia("DELETE FROM VEHICULO WHERE PROPIETARIO LIKE ?;");
                //Se le da valor al comodín de la consulta
                ps.setString(1, tDni.getText());
                //Se ejecuta la consulta
                int resultado = ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "¡VEHICULO ELIMINADO!", "Vehiculo", JOptionPane.INFORMATION_MESSAGE);
                //Se refresca la tabla
                RefrescarTabla();
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            // Cerrar statement
            if (ps != null) {
                try {
                    ps.close();
                } catch (SQLException ex) {
                    ex.getMessage();
                }
            }
        }
    }//GEN-LAST:event_bVehiculoActionPerformed
    /**
     * Método que elimina el propietario introducido
     *
     * @param evt parámetro que llama al evento que elimina a un propietario
     */
    private void bPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPropActionPerformed
        PreparedStatement ps = null;
        try {
            if (!compruebaDNI(tDni.getText())) {
                //Si el dni es incorrecto salta el error y deberemos volver a escribirlo
                JOptionPane.showMessageDialog(this, "!DNI INCORRECTO¡", "DNI incorrecto", JOptionPane.ERROR_MESSAGE);
                tDni.setText("");
            } else {
                //Se lanza la consulta
                ps = conn.prepararSentencia("DELETE FROM PROPIETARIO WHERE DNI LIKE ?;");
                //Se le da valor al comodín de la consulta
                ps.setString(1, tDni.getText());
                //Se ejecuta la consulta
                int resultado = ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "¡PROPIETARIO ELIMINADO!", "Propietario", JOptionPane.INFORMATION_MESSAGE);
                //Deja los campos vacíos
                limpiarDatos();
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            // Cerrar statement
            if (ps != null) {
                try {
                    ps.close();
                } catch (SQLException ex) {
                    ex.getMessage();
                }
            }
        }
    }//GEN-LAST:event_bPropActionPerformed
    /**
     * Método que rellena la tabla con los vehículos que posee un propietario
     */
    private void rellenaTabla() {
        try {
            //Lanzamos la consulta 
            PreparedStatement ps = conn.prepararSentencia("SELECT V.MATRICULA, V.MODELO, V.ANIO, concat_ws(' ',P.NOMBRE,P.APELLIDO)"
                    + "FROM VEHICULO V JOIN PROPIETARIO P ON(V.PROPIETARIO = P.DNI) WHERE V.PROPIETARIO LIKE ?");
            //Le damos valor al comodín de la consulta
            ps.setString(1, tDni.getText());
            //Ejecutamos la consulta
            ResultSet rs = ps.executeQuery();
            //Mientras haya datos, añadiremos filas a la tabla
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bProp;
    private javax.swing.JButton bVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tApellido;
    private javax.swing.JTextField tDni;
    private javax.swing.JTextField tLefono;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tProvincia;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
