/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexión.Conexion;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import marcobartolomesergioproyecto3.Excepcion;
import marcobartolomesergioproyecto3.ExportarXML;

/**
 * Clase que llama a las demás ventanas o clases.
 *
 * @author Sergio Marco
 * @version 23/05/2017
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Conexion conn;

    /**
     * Creates new form VentanaPrincipal
     *
     * @param conn parámetro que pasa la conexión
     */
    public VentanaPrincipal(Conexion conn) {
        this.conn = conn;
        setIconImage(new ImageIcon(getClass().getResource("..\\Imagenes\\icono.jpg")).getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        BañadeVehiculo = new javax.swing.JButton();
        BañadePropietario = new javax.swing.JButton();
        bListadoVehiculos = new javax.swing.JButton();
        bBajaProp = new javax.swing.JButton();
        bListadoProp = new javax.swing.JButton();
        bFicheroXML = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SMOTORS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        BañadeVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coche.jpg"))); // NOI18N
        BañadeVehiculo.setText("Añadir Vehículos ");
        BañadeVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BañadeVehiculoActionPerformed(evt);
            }
        });

        BañadePropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/persona.jpg"))); // NOI18N
        BañadePropietario.setText("Añadir Propietario");
        BañadePropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BañadePropietarioActionPerformed(evt);
            }
        });

        bListadoVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista.jpg"))); // NOI18N
        bListadoVehiculos.setText("Mostrar Listado de Vehículos");
        bListadoVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListadoVehiculosActionPerformed(evt);
            }
        });

        bBajaProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baja.jpg"))); // NOI18N
        bBajaProp.setText("Dar de baja a un propietario");
        bBajaProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBajaPropActionPerformed(evt);
            }
        });

        bListadoProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista.jpg"))); // NOI18N
        bListadoProp.setText("Mostrar un listado de propietarios");
        bListadoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListadoPropActionPerformed(evt);
            }
        });

        bFicheroXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exportar.jpg"))); // NOI18N
        bFicheroXML.setText("Exportar los datos a un fichero XML");
        bFicheroXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFicheroXMLActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bBajaProp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(BañadeVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BañadePropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bListadoProp, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))))
                .addGap(64, 64, 64)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bListadoVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFicheroXML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BañadeVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BañadePropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bListadoVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bFicheroXML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bListadoProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBajaProp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Al ejecutar este botón se exportará a un documento XML
     *
     * @param evt parámetro que llama al evento que exporta el código a
     * documento XML
     */
    private void bFicheroXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFicheroXMLActionPerformed
        //Instancio la clase
        ExportarXML e = new ExportarXML(conn);
        try {
            //Si el método da true se exportará si no saldrá un mensaje de error
            //y no se exportará
            if (e.exportar()) {
                JOptionPane.showMessageDialog(this, "Has exportado a XML con éxito", "Exportar", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido exportar a XML", "Exportar", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Excepcion ex) {
            JOptionPane.showMessageDialog(this, "No se ha podido exportar a XML", "Exportar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bFicheroXMLActionPerformed
    /**
     * Llama a la ventana que realiza un listado de propietarios
     *
     * @param evt parámetro que llama al evento que muestra la ventana que lista
     * propietarios
     */
    private void bListadoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListadoPropActionPerformed
        VentanaListadoPropietarios v = new VentanaListadoPropietarios(conn);
        v.setVisible(true);
    }//GEN-LAST:event_bListadoPropActionPerformed
    /**
     * Llama a la ventana que realiza la baja de un propietario
     *
     * @param evt parámetro que llama al evento que muestra la ventana que da de
     * baja propietarios
     */
    private void bBajaPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBajaPropActionPerformed
        VentanaBajaPropietario v = new VentanaBajaPropietario(conn);
        v.setVisible(true);
    }//GEN-LAST:event_bBajaPropActionPerformed
    /**
     * Llama a la ventana que realiza un listado de vehículos
     *
     * @param evt parámetro que llama al evento que muestra la ventana que lista
     * vehículos
     */
    private void bListadoVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListadoVehiculosActionPerformed
        VentanaListadoVehiculos v = new VentanaListadoVehiculos(conn);
        v.setVisible(true);
    }//GEN-LAST:event_bListadoVehiculosActionPerformed
    /**
     * Llama a la ventana que añade propietarios
     *
     * @param evt parámetro que llama al evento que muestra la ventana que añade
     * propietarios
     */
    private void BañadePropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BañadePropietarioActionPerformed
        VentanaAñadePropietario v = new VentanaAñadePropietario(conn);
        v.setVisible(true);
    }//GEN-LAST:event_BañadePropietarioActionPerformed
    /**
     * Llama a la ventana que añade vehículos
     *
     * @param evt parámetro que llama al evento que muestra la ventana que añade
     * vehículos
     */
    private void BañadeVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BañadeVehiculoActionPerformed
        VentanaAñadeVehiculos v = new VentanaAñadeVehiculos(conn);
        v.setVisible(true);
    }//GEN-LAST:event_BañadeVehiculoActionPerformed
    /**
     * Método que al cerrar la ventana cierre la conexión y salga del programa o
     * no muestre nada.
     */
    public void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "En realidad desea realizar cerrar la aplicacion", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            conn.Desconectar();
            System.exit(0);
        } else {
        }
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BañadePropietario;
    private javax.swing.JButton BañadeVehiculo;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton bBajaProp;
    private javax.swing.JButton bFicheroXML;
    private javax.swing.JButton bListadoProp;
    private javax.swing.JButton bListadoVehiculos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
